{"name": "test_assert_nums", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 1 == 0", "trace": "num_1 = 1, num_2 = 0\n\n    @pytest.mark.xfail\n    def test_assert_nums(num_1=1, num_2=0):\n>       assert num_1 == num_2\nE       assert 1 == 0\n\ntest_.py:5: AssertionError"}, "attachments": [{"name": "log", "source": "cc634a6d-3895-486a-a409-a8a19c66d71e-attachment.txt", "type": "text/plain"}], "start": 1684185216578, "stop": 1684185216578, "uuid": "fc20662f-26d6-4749-9f66-d3dc0bcb360e", "historyId": "9efadaba1b81c6729cfe7fb03c1b015c", "testCaseId": "9efadaba1b81c6729cfe7fb03c1b015c", "fullName": "Selenium_commands.test_#test_assert_nums", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "Selenium_commands"}, {"name": "suite", "value": "test_"}, {"name": "host", "value": "DESKTOP-LMN1V1H"}, {"name": "thread", "value": "16820-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Selenium_commands.test_"}]}