{"name": "test_assert_nums", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 1 == 0", "trace": "num_1 = 1, num_2 = 0\n\n    @pytest.mark.xfail\n    def test_assert_nums(num_1=1, num_2=0):\n>       assert num_1 == num_2\nE       assert 1 == 0\n\ntest_.py:5: AssertionError"}, "attachments": [{"name": "log", "source": "b94bff5a-8b9f-496d-b8d2-2c21719901a2-attachment.txt", "type": "text/plain"}], "start": 1684425534141, "stop": 1684425534142, "uuid": "1c5dd606-d41d-4cf1-9d68-69a80899f9de", "historyId": "9efadaba1b81c6729cfe7fb03c1b015c", "testCaseId": "9efadaba1b81c6729cfe7fb03c1b015c", "fullName": "Selenium_commands.test_#test_assert_nums", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "Selenium_commands"}, {"name": "suite", "value": "test_"}, {"name": "host", "value": "DESKTOP-LMN1V1H"}, {"name": "thread", "value": "17580-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Selenium_commands.test_"}]}