{"name": "test_assert_nums", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 1 == 0", "trace": "num_1 = 1, num_2 = 0\n\n    @pytest.mark.xfail\n    def test_assert_nums(num_1=1, num_2=0):\n>       assert num_1 == num_2\nE       assert 1 == 0\n\ntest_.py:5: AssertionError"}, "attachments": [{"name": "log", "source": "70777fa9-9455-4793-8bd9-4dbaded583d2-attachment.txt", "type": "text/plain"}], "start": 1684258042085, "stop": 1684258042085, "uuid": "33144510-8828-46ba-913b-e4d3928f673a", "historyId": "9efadaba1b81c6729cfe7fb03c1b015c", "testCaseId": "9efadaba1b81c6729cfe7fb03c1b015c", "fullName": "Selenium_commands.test_#test_assert_nums", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "Selenium_commands"}, {"name": "suite", "value": "test_"}, {"name": "host", "value": "DESKTOP-LMN1V1H"}, {"name": "thread", "value": "18388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Selenium_commands.test_"}]}