{"name": "test_assert_nums", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 1 == 0", "trace": "num_1 = 1, num_2 = 0\n\n    @pytest.mark.xfail\n    def test_assert_nums(num_1=1, num_2=0):\n>       assert num_1 == num_2\nE       assert 1 == 0\n\ntest_.py:5: AssertionError"}, "attachments": [{"name": "log", "source": "390b783c-15db-4672-bd06-9b5aa9c935d4-attachment.txt", "type": "text/plain"}], "start": 1684090528650, "stop": 1684090528650, "uuid": "8d9e0203-7fe0-42c7-bc77-b7c0ad73ff3c", "historyId": "9efadaba1b81c6729cfe7fb03c1b015c", "testCaseId": "9efadaba1b81c6729cfe7fb03c1b015c", "fullName": "Selenium_commands.test_#test_assert_nums", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "Selenium_commands"}, {"name": "suite", "value": "test_"}, {"name": "host", "value": "DESKTOP-LMN1V1H"}, {"name": "thread", "value": "5804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Selenium_commands.test_"}]}